repo:
  scanPath: ./tmp
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: reese codes
  description: ğŸğŸ’»ğŸğŸ’»
server:
  name: localhost
  host: 127.0.0.1
  port: 5555
